---
sudo: required
dist: trusty
language: python
python: "2.7"
cache:
  directories:
    - "$(npm config get prefix)/bin"

services:
  - docker

matrix:
  - fast_finish: true

env:
  - TEST_RUN="docker build -qt eggshell/replay_processing replay_processing/"
  - TEST_RUN="cd sc2_util && docker build -qt eggshell/sc2_util sc2_util"
  - TEST_RUN="tests/markdownlint-cli-test.sh"

install:
  - nvm deactivate
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script: "$TEST_RUN"

notifications:
  email: false
