---
sudo: required
dist: trusty
language: python
python: "2.7"
cache:
  directories:
    - "$(npm config get prefix)/bin"

services:
  - docker

matrix:
  - fast_finish: true

env:
  - TEST_RUN="tests/build_replay_processing.sh"
  - TEST_RUN="tests/build_sc2_util.sh"
  - TEST_RUN="tests/markdownlint-cli-test.sh"

install:
  - nvm deactivate
  - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script: "$TEST_RUN"

notifications:
  email: false
