---
sudo: required
dist: trusty
language: python
python: "2.7"
cache: pip

services:
  - docker

matrix:
  - fast_finish: true

env:
  - TEST_RUN="docker build -qt eggshell/sc2_base sc2_base/"
  - TEST_RUN="docker build -qt eggshell/replay_processing replay_processing/"
  - TEST_RUN="cd util && docker build -qt eggshell/util util"

script: "$TEST_RUN"
