---
sudo: required
dist: trusty
language: python
python: "2.7"
cache: pip

services:
  - docker

matrix:
  - fast_finish: true

env:
  - TEST_RUN="docker build -qt eggshell/replay_processing replay_processing/"
  - TEST_RUN="cd sc2_util && docker build -qt eggshell/sc2_util sc2_util"

script: "$TEST_RUN"
