#!/bin/bash

inotifywait -m /replays -e create -e moved_to |
    while read path action file; do
        echo "The file '$file' appeared in directory '$path' via '$action'"
        docker run -v replays:/replays eggshell/replay_processing /bin/sh -c "replayscan -R /replays"
    done
