FROM eggshell/sc2_base:latest

RUN pip install -e git+git://github.com/StoicLoofah/spawningtool.git#egg=spawningtool
RUN pip install -e git+git://github.com/nibalizer/replay_processing.git#egg=replay_processing
